<?php
/**
 *
 */

namespace AMP_WP_Compatibility_Suite\Inc\Generator;

class Widgets extends Base {

	public function generate() {

		parent::generate(); // TODO: Change the autogenerated stub

		$posts = get_posts( [
			'name'      => 'amp-wp-compatibility-widgets',
			'post_type' => 'page',
			'fields'    => 'ids',
		] );

		if ( empty( $posts ) ) {
			$page_args = [
				'post_type'  => 'page',
				'post_title' => 'AMP WP Compatibility Widgets',
				'post_name'  => 'amp-wp-compatibility-widgets',
			];

			$post_id = self::create_and_get_post( $page_args );
		} else {
			$post_id = $posts[0];
		}

		if ( ! empty( $post_id ) && ! is_wp_error( $post_id ) && 0 < intval( $post_id ) ) {
			\WP_CLI::success( 'Widget Post ID: ' . $post_id );
		} else {
			\WP_CLI::warning( 'Failed to create widget page: ' );
		}

	}

}