on:
  push:
    branches:
      - main

name: Deploy and Slack Notification
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        credentials_file_path: /tmp/creds

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure deployment files
      run: echo "$ENV" | base64 -d > .env && echo "$APP_YAML" | base64 -d > app.yaml
      env:
        ENV: ${{ secrets.ENV }}
        APP_YAML: ${{ secrets.APP_YAML }}

    - name: Install modules and asset build
      run: npm i && npm run prod

    - name: Deploy to App Engine
      run: gcloud app deploy --promote -q

    - name: Remove extra files
      run: rm .env /tmp/creds app.yaml

    - name: Deploy to Compute Engine
      uses: rtCamp/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: bots-amp-comp-db
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "App Engine Instance"
        SLACK_MESSAGE: "Deployed Server to https://test-amp-comp-db.uc.r.appspot.com/ :rocket:\n\n*Compute Instance*\nDeployed Worker to `root@worker.rt.gw`\n\n*Message*\n${{ github.event.head_commit.message }}"

    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
