<?php
/**
 * Generator class for widgets.
 *
 * @package amp-wp-dummy-data-generator
 */

namespace AMP_WP_Dummy_Data_Generator\Inc\Generator;

use AMP_WP_Dummy_Data_Generator\Inc\Analyzer\Widget;

/**
 * Class Widgets
 */
class Widgets extends Base {

	/**
	 * Generator function.
	 *
	 * @return void
	 */
	public function generate() {

		parent::generate(); // TODO: Change the autogenerated stub.

		global $wp_widget_factory;

		$widgets = $wp_widget_factory->widgets;

		foreach ( $widgets as $widget_class => $widget_object ) {

			$instance = new Widget( $widget_object );

			print_r($instance);

		}

	}

}
